# Resume Dataset

In [7]:
import pandas as pd 
import numpy as np

In [2]:
resume_df = pd.read_csv('..//data//raw//Resume//Resume_dataset.csv')
resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
resume_df.shape

(2484, 4)

In [ ]:
resume_df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='str')

# Question Dataset

### For this Project I need only 2 Features i.e. Resume_str and Category

In [11]:
resume_df = resume_df[
    [
        "Resume_str",
        "Category"
    ]
]

resume_df.head()

                                          Resume_str Category
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1           HR SPECIALIST, US HR OPERATIONS      ...       HR
2           HR DIRECTOR       Summary      Over 2...       HR
3           HR SPECIALIST       Summary    Dedica...       HR
4           HR MANAGER         Skill Highlights  ...       HR

In [10]:
resume_df.isnull().sum()

Resume_str    0
Category      0
dtype: int64

In [9]:
resume_df['Category'].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [12]:
print(resume_df['Category'].nunique())

24

In [13]:
resume_df.to_csv('..//data//processed//resume_clean_base.csv', index=False)