In [2]:
import pandas as pd 

# re = Regular Expression
import re

In [3]:
resume_df = pd.read_csv("..//data//processed//resume_clean_base.csv")
resume_df.head()

                                          Resume_str Category
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1           HR SPECIALIST, US HR OPERATIONS      ...       HR
2           HR DIRECTOR       Summary      Over 2...       HR
3           HR SPECIALIST       Summary    Dedica...       HR
4           HR MANAGER         Skill Highlights  ...       HR

In [4]:
def clean_resume(text):

    # Remove URLs
    text = re.sub(
        r"http\s+|www\s+",
        " ",
        text
    )
    
    # Remove email addresses
    text = re.sub(
        r"\s+@\s+",
        " ",
        text
    )

    # Remove phone numbers
    text = re.sub(
        r"\+?\d\s\-]{8,}",
        " ",
        text
    )

    # Remove HTML tags
    text = re.sub(
        r"<.*?>",
        " ",
        text
    )

    # Remove special characters
    text  = re.sub(
        r"[^a-zA-Z ]",
        " ",
        text 
    )

    text = text.lower()

    # Remove extra spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text

In [6]:
resume_df["clean_resume_text"] = resume_df["Resume_str"].apply(clean_resume)
resume_df.head()

,Resume_str,Category,clean_resume_text
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,hr administrator marketing associate hr admin...
1,"HR SPECIALIST, US HR OPERATIONS ...",HR,hr specialist us hr operations summary versat...
2,HR DIRECTOR Summary Over 2...,HR,hr director summary over years experience in ...
3,HR SPECIALIST Summary Dedica...,HR,hr specialist summary dedicated driven and dy...
4,HR MANAGER Skill Highlights ...,HR,hr manager skill highlights hr skills hr depa...

In [7]:
resume_df["clean_resume_text"].str.len().describe()

count     2484.000000
mean      5651.883655
std       2573.329646
min          1.000000
25%       4592.500000
50%       5265.000000
75%       6520.250000
max      34317.000000
Name: clean_resume_text, dtype: float64

In [8]:
# Remove Empty Rows
resume_df = resume_df[resume_df['clean_resume_text'].str.len()>20]
resume_df.head()

,Resume_str,Category,clean_resume_text
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,hr administrator marketing associate hr admin...
1,"HR SPECIALIST, US HR OPERATIONS ...",HR,hr specialist us hr operations summary versat...
2,HR DIRECTOR Summary Over 2...,HR,hr director summary over years experience in ...
3,HR SPECIALIST Summary Dedica...,HR,hr specialist summary dedicated driven and dy...
4,HR MANAGER Skill Highlights ...,HR,hr manager skill highlights hr skills hr depa...

In [9]:

resume_df.to_csv("..//data//processed//resume_processed.csv", index=False)